### ISSUE TITLE
CSS & Other Small Issues

### ISSUE THREAD

**Issue by sponcey** [undercasetype/fraunces-minisite#12]
I've noticed some issues with the CSS between the desktop and mobile that would be great to take a look at.

- The figure tags look great on desktop, but is there a way to force everything to center in mobile? 
- The scrolling styles, how did you generate the list of instances? We can update this now.
- also, if I want to update the stickers in the future, how do I do that?

**Comment by RoelN** [comment]
Figure tags are fixed in e7f235a468eafe6b851d9be2182544328216a538!

Re: the scrolling instances: I can take the list of current named instances and re-generate them?

Re: stickers, I'm working on a refactor of this code. Will show you how to add when it's ready!
