### ISSUE TITLE
Update list of instances in the marquee

### ISSUE THREAD

**Issue by RoelN** [undercasetype/fraunces-minisite#27]
Current ones were manually added at start of project. Check out which ones are in the font and make a list of them

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/4570664/73055871-02b64800-3e8e-11ea-916c-2aac8949982d.png">

**Comment by RoelN** [comment]
https://github.com/undercasetype/fraunces-minisite/issues/12

**Comment by sponcey** [comment]
We just got word from the engineering team that we will need to change some of the axis values, which will effect the instance names. I'll let you know when we have that locked down.

**Comment by RoelN** [comment]
Thanks for the heads up! Let's do this when the names are final.

**Comment by sponcey** [comment]
Okay, it looks like we're finally ready with the instance names/axis names/and mastering is pretty much done. You can start incorporating the most recent fonts [here.](https://github.com/undercasetype/Fraunces/tree/master/fonts)

**Comment by RoelN** [comment]
The new named instances aren't really suitable for a scrolling text I though ("144pt S100 SemiBold") so improvised a bit. Works nicely, except SoftMin/SoftMid/SoftMax. Maybe change that to Soft/Softer/Softest?

![image](https://user-images.githubusercontent.com/4570664/84021283-9c394e80-a984-11ea-9bf0-8c2a517e59ad.png)

@sponcey What do you think?

**Comment by sponcey** [comment]
Do you have a screenshot of what it looks like with the actual instance names? This looks a little confusing to me, since these don't correlate to the specified instance names.

**Comment by RoelN** [comment]
I'll make one tomorrow. I think if you don't know that these are named instance names, it'll look like gobbledygook:

`
9pt S000 Thin, 9pt S000 Light, 9pt S000 Regular, 9pt S000 SemiBold, 9pt S000 Bold, 9pt S000 Black, 9pt S050 Thin, 9pt S050 Light, 9pt S050 Regular, 9pt S050 SemiBold, 9pt S050 Bold, 9pt S050 Black, 9pt S100 Thin, 9pt S100 Light, 9pt S100 Regular, 9pt S100 SemiBold, 9pt S100 Bold, 9pt S100 Black, 72pt S000 Thin, 72pt S000 Light, 72pt S000 Regular, 72pt S000 SemiBold, 72pt S000 Bold, 72pt S000 Black, 72pt S050 Thin, 72pt S050 Light, 72pt S050 Regular, 72pt S050 SemiBold, 72pt S050 Bold, 72pt S050 Black, 72pt S100 Thin, 72pt S100 Light, 72pt S100 Regular, 72pt S100 SemiBold, 72pt S100 Bold, 72pt S100 Black, 144pt S000 Thin, 144pt S000 Light, 144pt S000 Regular, 144pt S000 SemiBold, 144pt S000 Bold, 144pt S000 Black, 144pt S050 Thin, 144pt S050 Light, 144pt S050 Regular, 144pt S050 SemiBold, 144pt S050 Bold, 144pt S050 Black, 144pt S100 Thin, 144pt S100 Light, 144pt S100 Regular, 144pt S100 SemiBold, 144pt S100 Bold, 144pt S100 Black`

**Comment by RoelN** [comment]
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/4570664/84127034-fe568a00-aa3e-11ea-9911-5f66b5e37f0d.png">

Actually not that bad, eh!
