### ISSUE TITLE
Investigate sticker positioning bug

### ISSUE THREAD

**Issue by RoelN** [undercasetype/fraunces-minisite#35]
Offset ~ 200px to top of where you click

Can only drag on X axis?

**Comment by sgoodspeed** [comment]
Hi Roel! Wanted to offer more specific details of the bug I experienced:

- Occurred after basically filling the screen with stickers as much as possible, then hitting refresh
- Clicking anywhere on screen locked stickers to the same horizontal axis, about one third down the sticker plane
- Clicking and holding on stickers that were placed in locations below that axis on load and moving the mouse also snapped them to that same x-axis position
- Stickers can be placed above that axis as normal
- Bug persisted after refreshing the page (still happening, for me)

Hope that helps!

**Comment by RoelN** [comment]
Thanks @sgoodspeed for the thorough report! We're currently refactoring all code related to the stickers, and we don't see it happen On Our Machines™, so I'm closing the issue. By all means, do re-open if the bug still happens at your side when the new site preview is delivered.
