### ISSUE TITLE
Deploy to main project gh-pages

### ISSUE THREAD

**Issue by davelab6** [undercasetype/fraunces-minisite#40]
Please deploy to https://github.com/undercasetype/fraunces gh-pages branch and then remove the one in this repo :)

**Comment by sponcey** [comment]
I might get a custom URL, I'll look into that.

**Comment by pascalw** [comment]
@sponcey did you decide on the custom domain? If you have a custom domain I don't think it matters on which repo the `gh-pages` branch exists.

If you don't, I can update the CI configuration to deploy to the `gh-pages` branch on the main Fraunces repo. Let me know!

**Comment by sponcey** [comment]
I did! I was able to set it up under fraunces.undercase.xyz :)

**Comment by pascalw** [comment]
Awesome! I'll close this issue then.
