### ISSUE TITLE
shorten "flip" section

### ISSUE THREAD

**Issue by sponcey** [undercasetype/fraunces-minisite#46]
As discussed with the Google Design team, I think the best way to handle the length of the "flip" section is to shorten it:

– Change axis tags to "opsz", "GOOF", "wght". Earlier in the specimen we can explain the abbreviations.
– Remove "Family" and "Style" columns? Let's italicize "for Shopping", so that users can see both Roman and Italic at the same time. I think the most important part of this section is to convey what the instance values mean/which axis they are connected too.

**Comment by sponcey** [comment]
Another thought, maybe we don't need to eliminate "style" if changing to "opsz" allows that column to go a lot shorter.

**Comment by RoelN** [comment]
How about this, as per @sgoodspeed in https://github.com/undercasetype/fraunces-minisite/pull/58#issuecomment-581505337? //cc @sponcey 

![image](https://user-images.githubusercontent.com/4570664/73843397-de0f8800-481e-11ea-82f2-bed4b50cbea9.png)

**Comment by RoelN** [comment]
Closing this, let's open a new issue if this is not satisfactory
