### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by RoelN** [undercasetype/fraunces-minisite#73]
@sponcey @davelab6 Who's tracking code should we use?

**Comment by davelab6** [comment]
Unless we want to have the canonical URL of the site as googlefonts.github.io/fraunces then we can't use a Google Fonts team code.

**Comment by RoelN** [comment]
I noticed other Google Font specimen sites do not show a cookie consent warning/alert. Is there an official policy we should follow, @davelab6?

**Comment by RoelN** [comment]
Relevant: https://github.com/arrowtype/recursive-minisite/issues/64#issuecomment-593197732

**Comment by davelab6** [comment]
Do they use cookies? 

> Unless we want to have the canonical URL of the site as googlefonts.github.io/fraunces 

We don't, so this site should use a tracking code created by @sponcey

**Comment by davelab6** [comment]
> Is there an official policy we should follow, @davelab6?

No; the policy is to comply with local legal requirements. Assuming this site is hosted at https://undercasetype.github.io/fraunces or another domain operated by @sponcey, he's ultimately responsible for complying with USA and NYS requirements.

**Comment by RoelN** [comment]
@sponcey Can you pass me a GA snippet under your Google account?

**Comment by RoelN** [comment]
Added in f1e3602c3dec609933094a749552fdf4c09116b8
