### ISSUE TITLE
Hook up Github Pages to fraunces.undercase.xyz domain

### ISSUE THREAD

**Issue by RoelN** [undercasetype/fraunces-minisite#78]

**Comment by davelab6** [comment]
https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site

**Comment by pascalw** [comment]
@RoelN this is already the case?

```sh
ϟ dig fraunces.undercase.xyz

fraunces.undercase.xyz. 3600    IN      CNAME   undercasetype.github.io.
undercasetype.github.io. 3600   IN      A       185.199.109.153
undercasetype.github.io. 3600   IN      A       185.199.110.153
undercasetype.github.io. 3600   IN      A       185.199.111.153
undercasetype.github.io. 3600   IN      A       185.199.108.153
```

**Comment by RoelN** [comment]
I love it when _stuff just works_. Thanks again!

**Comment by RoelN** [comment]
Apparently new deploys overwrite the auto-generated CNAME file in the gh-pages branch. At least, that's my current assumption. Re-opening this issue to keep track of a solution.

**Comment by pascalw** [comment]
@RoelN are you sure that's the case? There have been many deployments between when the domain was configured (10 days ago) and today.

https://github.com/undercasetype/fraunces-minisite/deployments/activity_log

**Comment by RoelN** [comment]
It's working now, perhaps because @sponcey fixed it after the meeting we just had?

**Comment by RoelN** [comment]
(I just forced a new build, perhaps I'll break things again 😊 )

**Comment by pascalw** [comment]
Looks like it broke again! 😱

The docs indeed do [mention](https://help.github.com/en/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages#cname-errors) that a CNAME file is required (in the build output). I'll create a PR for it.

**Comment by pascalw** [comment]
I guess that was it, it's back 🎉

**Comment by RoelN** [comment]
Thanks both!!
