### ISSUE TITLE
opsz min value in CSS to 9.1

### ISSUE THREAD

**Issue by sponcey** [undercasetype/fraunces-minisite#89]
For the flip section, as well as the slider sections, how can we set the opsz value to 9.001? This is a bug with the browser that causes opsz 9 to default to opsz 144): [https://github.com/undercasetype/Fraunces/issues/56](https://github.com/undercasetype/Fraunces/issues/56)

**Comment by RoelN** [comment]
Ah! I've seen that value in one of your commits but I might have "normalized" it to 9 when working on the same code.

Setting it to `9.0001` in sliders min attributes and variables should fix it. Will pick up on Monday!

**Comment by RoelN** [comment]
Looking at https://github.com/undercasetype/Fraunces/issues/56, this workaround doesn't seems to be needed
