### ISSUE TITLE
add link to minisite repo

### ISSUE THREAD

**Issue by arrowtype** [undercasetype/fraunces-minisite#93]
Amazing site! I just clone the repo and built it, and good goof, it's beautiful.

I noticed that there doesn't seem to be a link to the minisite repo, and there should be, per

https://github.com/arrowtype/recursive-minisite/issues/38

![image](https://user-images.githubusercontent.com/45946693/76030922-a7ec2380-5f04-11ea-9068-c01c42ce7e3f.png)

**Comment by RoelN** [comment]
@davelab6 @sponcey Assuming this is the case here too, let's add the link
