### ISSUE TITLE
It's unclear in hero that you can "stick" the stickers

### ISSUE THREAD

**Issue by arrowtype** [undercasetype/fraunces-minisite#94]
I scrolled past the hero, thinking the `just looking!` sticker was following my cursor around for no discernable reason. It was only by chance that I scrolled back up and clicked to see whether I could edit type that I realized the point of that interaction.

Maybe the first sticker could give people a stronger cue about what they can do in that section? Something cheesy like a sticker saying `click 'n' stick!` might fit in pretty well, or maybe there could be a little tool tip suggesting the user clicks/taps to lay down stickers.

Obviously not necessary, but just a thought, as I bet many people might miss the fun of this section, and that would be a shame! It's a really fun section. :)

**Comment by RoelN** [comment]
Hey, thanks! @sponcey if you dig this solution, could you create a sticker?

**Comment by sponcey** [comment]
Yeah, that sounds like an easy/quick fix!
